# CMake generated Testfile for 
# Source directory: /home/limes/Projects/calamares/src/libcalamares
# Build directory: /home/limes/Projects/calamares/build/src/libcalamares
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(libcalamarestest "/home/limes/Projects/calamares/build/libcalamarestest")
set_tests_properties(libcalamarestest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/limes/Projects/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/limes/Projects/calamares/CMakeModules/CalamaresAddTest.cmake;34;ecm_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;205;calamares_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresgeoiptest "/home/limes/Projects/calamares/build/libcalamaresgeoiptest")
set_tests_properties(libcalamaresgeoiptest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/limes/Projects/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/limes/Projects/calamares/CMakeModules/CalamaresAddTest.cmake;34;ecm_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;211;calamares_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamareslocaletest "/home/limes/Projects/calamares/build/libcalamareslocaletest")
set_tests_properties(libcalamareslocaletest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/limes/Projects/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/limes/Projects/calamares/CMakeModules/CalamaresAddTest.cmake;34;ecm_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;256;calamares_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresmodulesystemtest "/home/limes/Projects/calamares/build/libcalamaresmodulesystemtest")
set_tests_properties(libcalamaresmodulesystemtest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/limes/Projects/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/limes/Projects/calamares/CMakeModules/CalamaresAddTest.cmake;34;ecm_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;263;calamares_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresnetworktest "/home/limes/Projects/calamares/build/libcalamaresnetworktest")
set_tests_properties(libcalamaresnetworktest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/limes/Projects/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/limes/Projects/calamares/CMakeModules/CalamaresAddTest.cmake;34;ecm_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;269;calamares_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamarespackagestest "/home/limes/Projects/calamares/build/libcalamarespackagestest")
set_tests_properties(libcalamarespackagestest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/limes/Projects/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/limes/Projects/calamares/CMakeModules/CalamaresAddTest.cmake;34;ecm_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;275;calamares_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamarespartitiontest "/home/limes/Projects/calamares/build/libcalamarespartitiontest")
set_tests_properties(libcalamarespartitiontest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/limes/Projects/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/limes/Projects/calamares/CMakeModules/CalamaresAddTest.cmake;34;ecm_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;281;calamares_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamarespartitionkpmtest "/home/limes/Projects/calamares/build/libcalamarespartitionkpmtest")
set_tests_properties(libcalamarespartitionkpmtest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/limes/Projects/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/limes/Projects/calamares/CMakeModules/CalamaresAddTest.cmake;34;ecm_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;291;calamares_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresutilstest "/home/limes/Projects/calamares/build/libcalamaresutilstest")
set_tests_properties(libcalamaresutilstest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/limes/Projects/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/limes/Projects/calamares/CMakeModules/CalamaresAddTest.cmake;34;ecm_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;300;calamares_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresutilspathstest "/home/limes/Projects/calamares/build/libcalamaresutilspathstest")
set_tests_properties(libcalamaresutilspathstest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/limes/Projects/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/limes/Projects/calamares/CMakeModules/CalamaresAddTest.cmake;34;ecm_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;306;calamares_add_test;/home/limes/Projects/calamares/src/libcalamares/CMakeLists.txt;0;")
